name: Deploy to cloudflare workers

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths: 
      - 'packages/bakeoff1/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PACKAGE_PATH: packages/bakeoff1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install
        run: npm ci --workspace=${{ env.PACKAGE_PATH }}
      - name: Build
        run: |
          npm run gen --workspace=${{ env.PACKAGE_PATH }}
          npm run build --workspace=${{ env.PACKAGE_PATH }}
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
      - name: Deploy
        run: npx wrangler deploy
        working-directory: ${{ env.PACKAGE_PATH }}
        env:
          # Wrangler looks for these exact names by default
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_WORKERS_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}