name: Deploy to cloudflare workers

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths: 
      - 'packages/bakeoff1/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install
        run: npm ci --workspace=packages/bakeoff1
      - name: Build
        run: |
          npm ren gen
          npm run build
      - name: Deploy
        run: npx wrangler deploy
        env:
          # Wrangler looks for these exact names by default
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_WORKERS_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}