name: Deploy to Netlify

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths: 
      - 'packages/bakeoff3/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PACKAGE_PATH: packages/bakeoff3

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install
        run: npm ci --workspace=${{ env.PACKAGE_PATH }}
      - name: Build
        run: npm run build --workspace=${{ env.PACKAGE_PATH }}
      - name: Deploy
        run: npx netlify deploy --prod --no-build --dir "./packages/bakeoff3/dist" --site resume-project
        working-directory: ${{ env.PACKAGE_PATH }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
